### PR TITLE
Add irange_items

### PR DESCRIPTION
**Pull request by mbarkhau**
Before I write tests for this, could I have some feedback on whether or not this would be considered as something that would be merged?

### CODE REVIEW

**Comment by grantjenks** [comment]
Hi @mbarkhau. Thanks for asking and writing code!

While it's a simple change, it's not in itself very motivating. It's almost too simple.

Can you tell me more about your use case?

Seems like this would suffice your needs:

```python
from sortedcontainers import SortedDict as _SortedDict

class SortedDict(_SortedDict):
    def irange_items(self, *args, **kwargs):
        return iter((key, self[key]) for key in self.irange(*args, **kwargs))
```

Also, would you add `irange_key_items`?

**Comment by mbarkhau** [comment]
Subclassing is fine yes. My use case was partial reverse iteration. Not sure what you mean by {{irange_key_items}}, what would that do? Maybe you mean {{irange_keys}} and {{irange_values}} and yes those would of course make just as much sense if {{irange_items}} were to be added.

**Comment by grantjenks** [comment]
If you use a `key` function parameter then there's both an `irange` and `irange_key` method. The former applies the key function then does the bisecting and iterator construction. The latter skips the application of key function. The terminology is confusing because we refer to dicts as key/value pairs and the `SortedDict` also accepts a key-function to determine sort order.

Sounds like subclassing will work in this particular case. Let me know if the pattern crops up more often or you see it elsewhere.

**Comment by mbarkhau** [comment]
Sure thing, have a good one.

**Pull request closed without merging**
